language: java

jdk:
- oraclejdk8

branches:
  only:
  - master
  #- "/^v\\d+\\.\\d+\\.\\d+$/"

cache:
  directories:
  - $HOME/.m2/repository

# skip the default install step
install: true

#before_script:
#  - if [ ! -z "${GPG_SECRET_KEYS}" ]; then echo ${GPG_SECRET_KEYS} | base64 --decode | $GPG_EXECUTABLE --import; fi
#  - if [ ! -z "${GPG_OWNERTRUST}" ]; then echo ${GPG_OWNERTRUST} | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

script:
- cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean deploy
