language: java

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

sudo: required

services:
  - docker

before_install:
- docker pull jbmusso/gremlin-server
- docker run -d --name gremlin-server -p 8182:8182 jbmusso/gremlin-server:latest
- docker run -d --name gremlin-server-ssl -p 8183:8182 jbmusso/gremlin-server:latest conf/gremlin-server-secure.yaml
- while ! echo exit | nc localhost 8182; do sleep 5; done
- while ! echo exit | nc localhost 8183; do sleep 5; done

# skip the default install step
install: true

before_script:
  # start gremlin server containers
  - docker-compose up -d
  # wait for gremlin servers to be listening
  - while ! echo exit | nc localhost 8182; do sleep 5; done
  - while ! echo exit | nc localhost 8183; do sleep 5; done

script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean deploy

after_script:
  - docker-compose down
